// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ws.message.v1.proto

package ws_message_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Type int32

const (
	// 普通消息
	Type_Ordinary Type = 0
	// 系统消息
	Type_System Type = 1
	// 指令消息
	Type_Instruction Type = 2
)

var Type_name = map[int32]string{
	0: "Ordinary",
	1: "System",
	2: "Instruction",
}

var Type_value = map[string]int32{
	"Ordinary":    0,
	"System":      1,
	"Instruction": 2,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d4a5e15014642fd0, []int{0}
}

// RequestMsg:
type RequestMsg struct {
	From                 string   `protobuf:"bytes,1,opt,name=From,proto3" json:"From,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=To,proto3" json:"To,omitempty"`
	Time                 int64    `protobuf:"varint,3,opt,name=Time,proto3" json:"Time,omitempty"`
	T                    Type     `protobuf:"varint,4,opt,name=T,proto3,enum=ws.message.v1.Type" json:"T,omitempty"`
	Data                 string   `protobuf:"bytes,5,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestMsg) Reset()         { *m = RequestMsg{} }
func (m *RequestMsg) String() string { return proto.CompactTextString(m) }
func (*RequestMsg) ProtoMessage()    {}
func (*RequestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4a5e15014642fd0, []int{0}
}

func (m *RequestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestMsg.Unmarshal(m, b)
}
func (m *RequestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestMsg.Marshal(b, m, deterministic)
}
func (m *RequestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestMsg.Merge(m, src)
}
func (m *RequestMsg) XXX_Size() int {
	return xxx_messageInfo_RequestMsg.Size(m)
}
func (m *RequestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RequestMsg proto.InternalMessageInfo

func (m *RequestMsg) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *RequestMsg) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *RequestMsg) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *RequestMsg) GetT() Type {
	if m != nil {
		return m.T
	}
	return Type_Ordinary
}

func (m *RequestMsg) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// ResponseMsg:
type ResponseMsg struct {
	Code                 int64    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Ok                   bool     `protobuf:"varint,2,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseMsg) Reset()         { *m = ResponseMsg{} }
func (m *ResponseMsg) String() string { return proto.CompactTextString(m) }
func (*ResponseMsg) ProtoMessage()    {}
func (*ResponseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4a5e15014642fd0, []int{1}
}

func (m *ResponseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseMsg.Unmarshal(m, b)
}
func (m *ResponseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseMsg.Marshal(b, m, deterministic)
}
func (m *ResponseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseMsg.Merge(m, src)
}
func (m *ResponseMsg) XXX_Size() int {
	return xxx_messageInfo_ResponseMsg.Size(m)
}
func (m *ResponseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseMsg proto.InternalMessageInfo

func (m *ResponseMsg) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseMsg) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *ResponseMsg) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterEnum("ws.message.v1.Type", Type_name, Type_value)
	proto.RegisterType((*RequestMsg)(nil), "ws.message.v1.RequestMsg")
	proto.RegisterType((*ResponseMsg)(nil), "ws.message.v1.ResponseMsg")
}

func init() {
	proto.RegisterFile("ws.message.v1.proto", fileDescriptor_d4a5e15014642fd0)
}

var fileDescriptor_d4a5e15014642fd0 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x5f, 0x4b, 0x32, 0x41,
	0x14, 0xc6, 0xdf, 0x99, 0xdd, 0xd7, 0xec, 0x58, 0x26, 0x23, 0xc4, 0xb6, 0x37, 0x99, 0x57, 0x12,
	0xb8, 0xa2, 0x41, 0xd7, 0xd1, 0x3f, 0xe8, 0xc2, 0x84, 0x71, 0x2f, 0xba, 0x5d, 0xdd, 0xc3, 0x36,
	0xd8, 0xee, 0xb1, 0x99, 0x51, 0xf1, 0x33, 0xf4, 0x21, 0x83, 0x3e, 0x49, 0xec, 0x04, 0xca, 0xd6,
	0xdd, 0xc3, 0x39, 0x33, 0xbf, 0xf3, 0xe3, 0x81, 0xf6, 0xc6, 0x44, 0x39, 0x1a, 0x93, 0x64, 0x18,
	0xad, 0x87, 0xd1, 0x52, 0x93, 0x25, 0x71, 0x5c, 0x19, 0x86, 0xd7, 0x99, 0xb2, 0xaf, 0xab, 0x59,
	0x34, 0xa7, 0x7c, 0x90, 0x6f, 0x94, 0x5d, 0xd0, 0x66, 0x90, 0x51, 0xdf, 0xbd, 0xed, 0xaf, 0x93,
	0x37, 0x95, 0x26, 0x96, 0xb4, 0x19, 0xec, 0xe2, 0x0f, 0xa6, 0xfb, 0xc1, 0x00, 0x24, 0xbe, 0xaf,
	0xd0, 0xd8, 0xb1, 0xc9, 0x44, 0x08, 0xfe, 0xa3, 0xa6, 0x3c, 0x60, 0x1d, 0xd6, 0x3b, 0xbc, 0xad,
	0x7d, 0x7d, 0x9e, 0xf3, 0x17, 0x26, 0xdd, 0x4c, 0x9c, 0x02, 0x8f, 0x29, 0xe0, 0x95, 0x0d, 0x8f,
	0x49, 0x08, 0xf0, 0x63, 0x95, 0x63, 0xe0, 0x75, 0x58, 0xcf, 0x93, 0x2e, 0x8b, 0x0b, 0x60, 0x71,
	0xe0, 0x77, 0x58, 0xaf, 0x39, 0x6a, 0x47, 0x55, 0xfd, 0x78, 0xbb, 0x44, 0xc9, 0xe2, 0xf2, 0xdb,
	0x7d, 0x62, 0x93, 0xe0, 0x7f, 0x09, 0x94, 0x2e, 0x77, 0x1f, 0xa0, 0x21, 0xd1, 0x2c, 0xa9, 0x30,
	0x58, 0xda, 0x08, 0xf0, 0xef, 0x28, 0x45, 0x67, 0xe3, 0x49, 0x97, 0x45, 0x13, 0xf8, 0x64, 0xe1,
	0x2c, 0xea, 0x92, 0x4f, 0x16, 0x3b, 0x8c, 0xb7, 0xc7, 0x5c, 0x0e, 0xc1, 0x2f, 0xaf, 0x88, 0x23,
	0xa8, 0x4f, 0x74, 0xaa, 0x8a, 0x44, 0x6f, 0x5b, 0xff, 0x04, 0x40, 0x6d, 0xba, 0x35, 0x16, 0xf3,
	0x16, 0x13, 0x27, 0xd0, 0x78, 0x2a, 0x8c, 0xd5, 0xab, 0xb9, 0x55, 0x54, 0xb4, 0xf8, 0xe8, 0x19,
	0x60, 0x6c, 0xb2, 0x29, 0xea, 0xb5, 0x9a, 0xa3, 0xb8, 0x81, 0x83, 0x29, 0x16, 0x69, 0xe9, 0x70,
	0xf6, 0x4b, 0x7f, 0x5f, 0x56, 0x18, 0xfe, 0x59, 0xed, 0xd4, 0x67, 0x35, 0x57, 0xef, 0xd5, 0x77,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x27, 0xc1, 0xb5, 0xbc, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MsgServiceClient is the client API for MsgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgServiceClient interface {
	SendMsg(ctx context.Context, in *RequestMsg, opts ...grpc.CallOption) (*ResponseMsg, error)
}

type msgServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgServiceClient(cc grpc.ClientConnInterface) MsgServiceClient {
	return &msgServiceClient{cc}
}

func (c *msgServiceClient) SendMsg(ctx context.Context, in *RequestMsg, opts ...grpc.CallOption) (*ResponseMsg, error) {
	out := new(ResponseMsg)
	err := c.cc.Invoke(ctx, "/ws.message.v1.MsgService/SendMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServiceServer is the server API for MsgService service.
type MsgServiceServer interface {
	SendMsg(context.Context, *RequestMsg) (*ResponseMsg, error)
}

// UnimplementedMsgServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServiceServer struct {
}

func (*UnimplementedMsgServiceServer) SendMsg(ctx context.Context, req *RequestMsg) (*ResponseMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMsg not implemented")
}

func RegisterMsgServiceServer(s *grpc.Server, srv MsgServiceServer) {
	s.RegisterService(&_MsgService_serviceDesc, srv)
}

func _MsgService_SendMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).SendMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ws.message.v1.MsgService/SendMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).SendMsg(ctx, req.(*RequestMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _MsgService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ws.message.v1.MsgService",
	HandlerType: (*MsgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMsg",
			Handler:    _MsgService_SendMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ws.message.v1.proto",
}
